name: release
on:
  release:
    types: [created]

jobs:

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Set VERSION env
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0
      - uses: wangyoucao577/go-release-action@v1.39
        with:
          github_token: ${{ secrets.GPTPROFNEWTON_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.21.4"
          pre_command: export CGO_ENABLED=0
          build_flags: -v
          ldflags: -X 'main.version=${{env.VERSION}}'
          project_path: "cmd/"
          extra_files: LICENSE README.md
          retry: 10

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set VERSION env
        run: echo VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0
      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: laghoule/gptProfNewton
          username: ${{ github.actor }}
          password: ${{ secrets.GPTPROFNEWTON_TOKEN }}
          buildargs: VERSION
          registry: ghcr.io
          tags: "latest,${{ env.VERSION }}"
          tag_semver: true
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          VERSION: ${{ env.VERSION }}
        with:
          name: laghoule/gptProfNewton
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildargs: VERSION
          tags: "latest,${{ env.VERSION }}"
          tag_semver: true
